# Generated by Django 5.1.7 on 2025-03-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=50)),
                ('id_prompt', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('supporting_text', models.TextField(blank=True, null=True)),
                ('essay_title', models.CharField(blank=True, max_length=255, null=True)),
                ('essay_text', models.TextField()),
                ('essay_year', models.PositiveIntegerField(blank=True, null=True)),
                ('general_comment', models.TextField(blank=True, null=True)),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('c4', models.TextField(blank=True, null=True)),
                ('c5', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LlmsDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('sup_text', models.TextField(blank=True, null=True)),
                ('essay', models.TextField()),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('c4', models.TextField(blank=True, null=True)),
                ('c5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_c1', models.CharField(choices=[('human', 'Humano'), ('ia', 'IA')], max_length=5, verbose_name='Competência 1')),
                ('choice_c2', models.CharField(choices=[('human', 'Humano'), ('ia', 'IA')], max_length=5, verbose_name='Competência 2')),
                ('choice_c3', models.CharField(choices=[('human', 'Humano'), ('ia', 'IA')], max_length=5, verbose_name='Competência 3')),
                ('choice_c4', models.CharField(choices=[('human', 'Humano'), ('ia', 'IA')], max_length=5, verbose_name='Competência 4')),
                ('choice_c5', models.CharField(choices=[('human', 'Humano'), ('ia', 'IA')], max_length=5, verbose_name='Competência 5')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.feedbackdataset')),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.llmsdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.userprofile')),
            ],
            options={
                'verbose_name': 'Resposta do usuário',
                'verbose_name_plural': 'Respostas dos usuários',
                'unique_together': {('user', 'feedback', 'llm')},
            },
        ),
    ]
